# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  groups:
    python-packages:
      patterns:
        - "*"
      - name: Dependabot Alert Export
  # You may pin to the exact commit or the version.
  # uses: ambilykk/dependabot-alert-export@4d2c6759ed70553c5970b53497b55027cfd21558
        uses: ambilykk/dependabot-alert-export@v1.0
        with:
    # GitHub token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #'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'
    # Organization name
          org_name: 'coolreshu16'
    # Repository name
          repo_name: 'Coolreshu16/Vulnerable-app'
    # CSV File path
          csv_path: data/vulnerability.csv
